### ISSUE TITLE
How to reconnect?

### ISSUE THREAD

**Issue by DeployChef** [nats-io/stan.net#136]
If i turn off one node i get timeout exception and crush my app. What i do wrong?

```
 var cf = new StanConnectionFactory();
            var opts = StanOptions.GetDefaultOptions();
            opts.NatsURL = "nats://127.0.0.1:4222,nats://127.0.0.1:4223,nats://127.0.0.1:4224";
            using (var c = cf.CreateConnection("test-cluster", "appname", opts))
            {
                using (c.Subscribe("foo", (sender, handlerArgs) => Console.WriteLine(
                    System.Text.Encoding.UTF8.GetString(handlerArgs.Message.Data))))
                {
                    while (true)
                    {
                        c.Publish("foo", System.Text.Encoding.UTF8.GetBytes("hello"));
                        await Task.Delay(300);
                    }
                   
                }
            }
```

**Comment by ColinSullivan1** [comment]
@DeployChef, thanks for raising this issue:

I tested with your code and this exception was thrown:
```text
Unhandled Exception: STAN.Client.StanException: Timeout occurred.
   at STAN.Client.PublishAck.wait()
   at STAN.Client.Connection.Publish(String subject, Byte[] data)
   at ConsoleApp1.Program.Main(String[] args) in 
```

Is that what you were seeing?  If so, this is a valid exception - you timed out on your publish ack, so upon catching the exception you can choose to resend, log, etc.

**Comment by DeployChef** [comment]
I set try{}catch and i want on second try get reconnected producer, but reconnect not happen...
It is only working when I set nats options. 
`
Options nopts = ConnectionFactory.GetDefaultOptions();
                nopts.MaxReconnect = -1;
                nopts.MaxPingsOut = 2;
                nopts.PingInterval = 500;
                nopts.Servers = new[] { "nats://127.0.0.1:4223", "nats://127.0.0.1:4224" };
`

Why reconnect don't working with Stan pattern.

How do i can have reconnect with Stan classes only?

**Comment by DeployChef** [comment]
My publish -
` using (c2.Subscribe("foo", (sender, handlerArgs) => Console.WriteLine(
                        System.Text.Encoding.UTF8.GetString(handlerArgs.Message.Data))))
                    {
                        Console.WriteLine("Connected. ConnServ {0}.", c?.NATSConnection?.ConnectedUrl);

                        while (true)
                        {

                            Console.WriteLine("Publishing.  ConnState {0}.", c?.NATSConnection?.State);
                            try
                            {
                                c.Publish("foo", System.Text.Encoding.UTF8.GetBytes("hello"));
                            }
                            catch (Exception e)
                            {
                                System.Console.WriteLine("exception:  {0}", e.Message);
                            }

                            await Task.Delay(1000);
                        }

                    }`

**Comment by DeployChef** [comment]
With stan option I get deadlock after two timeout exception :(

**Comment by DeployChef** [comment]
Working:

          Options nopts = ConnectionFactory.GetDefaultOptions();
            nopts.MaxReconnect = Options.ReconnectForever;
            nopts.MaxPingsOut = 2;
            nopts.PingInterval = 500;
            nopts.Servers = new[] { "nats://127.0.0.1:4224", "nats://127.0.0.1:4224" };
            nopts.ReconnectedEventHandler = (o, a) =>
            {
                Debug.WriteLine("Reconnected.");
            };
            var nc = new ConnectionFactory().CreateConnection(nopts);

            // Setup NATS streaming connection
            StanOptions stanOnp = StanOptions.GetDefaultOptions();
            stanOnp.NatsConn = nc;

Not working: (deadlock after second try to send) 

```
var stanOnp = StanOptions.GetDefaultOptions();

stanOnp.NatsURL = "nats://127.0.0.1:4223,nats://127.0.0.1:4224";

stanOnp.PingInterval = 100;
```

**Comment by DeployChef** [comment]
But I think it must to work with only stan configurating, maybe add this configs to stan options?

```
 nopts.MaxReconnect = Options.ReconnectForever;
        nopts.MaxPingsOut = 2;
        nopts.PingInterval = 500;
```

**Comment by DeployChef** [comment]
Another one trouble... When I use nats options, and turn off all streaming servers, my producer try to reconnect, if i turn on servers - I get deadlock while reconnecting....

**Comment by DeployChef** [comment]
Deadlock happen when i turn off leader node.....

**Comment by DeployChef** [comment]
When producer lost connection and I try to dispose connection - I get deadlock too

**Comment by ColinSullivan1** [comment]
Would you have a stack trace of the deadlocks you are seeing?  I'll run some tests and see if this is easily reproducible.

**Comment by DeployChef** [comment]
I create repository with console app that shows deadlock in different actions.
https://github.com/DeployChef/NatsStreamingClientTrouble
docker compose for local cluster included.

**Comment by ColinSullivan1** [comment]
Thank you, much appreciated!  I was able to reproduce the problem. 

It looks like there is a timeout that is not being set correctly.  I will get this fixed as a soon as I can, likely this weekend or early next week.

**Comment by DeployChef** [comment]
Thanks! ;)
