### ISSUE TITLE
Disposing NATSConnection immediately after unsubscribing throws StanBadSubscriptionException

### ISSUE THREAD

**Issue by ibrahimuludag** [nats-io/stan.net#80]
The following code throws StanBadSubscriptionException. I have 50 subscriptions in the _subscriptions array. 

```
foreach (var subscription in _subscriptions) {
    subscription.Unsubscribe();
}
_stanConnection.NATSConnection.Dispose();
_stanConnection.Dispose();
```
The error is as below
```
Failed to stop service. STAN.Client.StanBadSubscriptionException: Invalid subscription.
   at STAN.Client.AsyncSubscription.unsubscribe(Boolean close)
   at STAN.Client.AsyncSubscription.Unsubscribe()

```

But if I put a delay, everything is OK. 

```
foreach (var subscription in _subscriptions) {
    subscription.Close();
}
Task.Delay(2000).ContinueWith((t) => {
    _stanConnection.NATSConnection.Dispose();
    _stanConnection.Dispose();
});
```

I think, Close() method does not finish closing when exiting the method.

**Comment by ColinSullivan1** [comment]
Hmm.   Thanks for reporting this.

**Comment by danielwertheim** [comment]
@ibrahimuludag @ColinSullivan1 I do understand that this is an old issue but I wonder if you can confirm if my sample below is correct and should have failed, because I failed to recreate the issue. I tried with a couple of NuGet package versions (0.2.0, 0.1.7 and 0.1.4).

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var clusterId = "test-cluster";
            var clientId = Guid.NewGuid().ToString("N");

            var cn = new StanConnectionFactory().CreateConnection(clusterId, clientId);
            var subs = new List<IStanSubscription>();

            for (var i = 0; i < 50; i++)
            {
                var x = i;
                subs.Add(cn.Subscribe("sub1", (_, ma) => { Console.WriteLine($"{x}"); }));
            }

            Console.WriteLine("Hit key to publish");
            Console.ReadKey();

            cn.Publish("sub1", new byte[0]);

            Console.WriteLine("Hit any key to exit");
            Console.ReadKey();

            foreach (var sub in subs)
            {
                sub.Unsubscribe();
            }

            cn.NATSConnection.Dispose();
            cn.Dispose();
        }
    }
```

**Comment by ColinSullivan1** [comment]
Thanks @danielwertheim - @ibrahimuludag, this looks to be resolved with the latest releases.  Please re-open if this continues to be an issue.
